POST http://127.0.0.1:5000/user/login
Content-Type: application/json

{
  "name": "user1",
  "password": "123456"
}

###
GET  http://127.0.0.1:5000/items/select/1


###
PUT  http://127.0.0.1:5000/items/update/30
Content-Type: application/json

{
  "dollar": "100",
  "plat": "test",
  "source": "test",
  "detail": "test",
  "is_income":"1"
}

###
DELETE  http://127.0.0.1:5000/items/delete/10


###
POST  http://127.0.0.1:5000/items/select/selectByJson
Content-Type: application/json
Cookie: user_id=10

{
  "is_income": "1",
  # "plat": "web",
  # "source": "web",
  # "detail": "3",
  "start_date": "2024-01-01",
  "end_date": "2025-10-31"
}

###
GET  http://127.0.0.1:5000/user/info/1


###
GET  http://127.0.0.1:5000/analysis/total?type=income

